#!/bin/bash
sudo cp -r reissue_book /usr/bin/;
sudo cp reissue /usr/bin/;
sudo chmod 755 /usr/bin/reissue;
sudo pip3 install selenium;
echo "#################################"
echo "Library Automation tool successfully installed";
echo "Type 'reissue' anywhere on terminal screeen :)"